### ISSUE TITLE
Add Swagger or add an invite to a Postman workspace so we can test the app

### ISSUE THREAD

**Issue by rrojan** [noxiousghost/air-quality-analyzer#3]
The existing documentation is good, but it would be cherry on top if we had a swagger interface, postman workspace, or something along those lines to test out the application quickly

**Comment by noxiousghost** [comment]
Here is the invitation of postman workspace
https://app.getpostman.com/join-team?invite_code=7f491bb18943d0a3a667301313405b75

**Comment by noxiousghost** [comment]
Thank you, I have mailed you the postman workspace invitation link.
